In [1]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [2]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/endoushougo/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/endoushougo/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.2-cp313-cp313-macosx_11_0_arm64.whl (9.9 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.2

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: pip3.13 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
import numpy as np
import pandas as pd
dic = {'a': ['Tokyo','Kanagawa','Chiba'],'b':['Saitama','Tochigi','Ibaraki']}
pd.DataFrame(dic)

          a        b
0     Tokyo  Saitama
1  Kanagawa  Tochigi
2     Chiba  Ibaraki

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('weather.csv',sep=',')
df.head(3)
df.head()       # (指定がない場合)前から5行を表示
df.tail()       # (指定がない場合)後ろから5行を表示

,date,ave_temperature,max_temperature,min_temperature,precipitation,daylight_hours,cloud_amount,ave_wind_speed,max_wind_speed,max_wind_direction
87,2019/5/27,26.1,32.4,19.9,NaN,12.6,5.0,3.0,6.1,南東
88,2019/5/28,23.5,28.1,19.1,1.0,1.2,10.0,5.8,9.0,南南西
89,2019/5/29,20.2,25.1,16.8,7.5,2.9,10.0,3.4,7.7,南南西
90,2019/5/30,21.2,26.0,16.6,0.0,12.2,5.8,3.6,7.7,南
91,2019/5/31,21.6,24.2,19.5,0.0,0.7,10.0,3.8,6.4,南

In [10]:
import numpy as np
import pandas as pd
df = pd.read_csv('weather.csv',sep=',')
print('df.index:', df.index)
pd.DataFrame(df)

df.index: RangeIndex(start=0, stop=92, step=1)

,date,ave_temperature,max_temperature,min_temperature,precipitation,daylight_hours,cloud_amount,ave_wind_speed,max_wind_speed,max_wind_direction
0,2019/3/1,8.8,13.1,6.5,1.5,2.4,8.8,2.0,5.0,北西
1,2019/3/2,10.3,14.7,6.4,NaN,9.6,5.3,3.6,7.7,北西
2,2019/3/3,6.5,10.4,4.4,13.5,0.0,10.0,2.7,4.6,北北西
3,2019/3/4,7.3,9.5,5.4,27.5,0.0,10.0,3.5,5.5,北西
4,2019/3/5,9.6,15.8,4.3,0.5,9.1,6.0,2.4,6.5,南南東
...,...,...,...,...,...,...,...,...,...,...
87,2019/5/27,26.1,32.4,19.9,NaN,12.6,5.0,3.0,6.1,南東
88,2019/5/28,23.5,28.1,19.1,1.0,1.2,10.0,5.8,9.0,南南西
89,2019/5/29,20.2,25.1,16.8,7.5,2.9,10.0,3.4,7.7,南南西
90,2019/5/30,21.2,26.0,16.6,0.0,12.2,5.8,3.6,7.7,南
91,2019/5/31,21.6,24.2,19.5,0.0,0.7,10.0,3.8,6.4,南

In [11]:
import numpy as np
import pandas as pd
df = pd.read_csv('weather.csv',sep=',')
df.head(3)

,date,ave_temperature,max_temperature,min_temperature,precipitation,daylight_hours,cloud_amount,ave_wind_speed,max_wind_speed,max_wind_direction
0,2019/3/1,8.8,13.1,6.5,1.5,2.4,8.8,2.0,5.0,北西
1,2019/3/2,10.3,14.7,6.4,NaN,9.6,5.3,3.6,7.7,北西
2,2019/3/3,6.5,10.4,4.4,13.5,0.0,10.0,2.7,4.6,北北西